### PR TITLE
Roof functions update

### PR DESCRIPTION
**Pull request by anthonyhauck**
- Added Roof By DXF
- Updated Roof By Sketch

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/35)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/35)* status: all files reviewed, 2 unresolved discussions (waiting on @anthonyhauck)

___
*[Roof/RoofByDXF/src/RoofByDXF.cs, line 134 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/35#-MIyU7BY1yui9yDNCCbm:-MIyU7BY1yui9yDNCCbn:b-t0w2lv) ([raw file](https://github.com/hypar-io/buildingblocks/blob/f5559af6f6d488711366531d2d3df2619d1d2212/Roof/RoofByDXF/src/RoofByDXF.cs#L134)):*
> ```Smalltalk
> }
> 
> //polygons = polygons.Skip(1).ToList();
> ```

Either delete this commented code or note why it's necessary
___
*[Roof/RoofByDXF/test/_input/DXFLOG.TXT, line 1 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/35#-MIyVBt7-zFcmpzzSsD6:-MIyVBt7-zFcmpzzSsD7:b-tknx99) ([raw file](https://github.com/hypar-io/buildingblocks/blob/f5559af6f6d488711366531d2d3df2619d1d2212/Roof/RoofByDXF/test/_input/DXFLOG.TXT#L1)):*
> ```
> DDS-CAD Viewer
> ```

I think we don't need to include this log file in the repo.

**Review by anthonyhauck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/35)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @wynged)

___
*[Roof/RoofByDXF/src/RoofByDXF.cs, line 134 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/35#-MIyU7BY1yui9yDNCCbm:-MIyezId7NZsZxJaJS4R:bmwbr9c) ([raw file](https://github.com/hypar-io/buildingblocks/blob/f5559af6f6d488711366531d2d3df2619d1d2212/Roof/RoofByDXF/src/RoofByDXF.cs#L134)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

Either delete this commented code or note why it's necessary
</blockquote></details>

Adding a comment as to why it's retained.
___
*[Roof/RoofByDXF/test/_input/DXFLOG.TXT, line 1 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/35#-MIyVBt7-zFcmpzzSsD6:-MIyfF145uRVsNPL4tZv:b-itbn4v) ([raw file](https://github.com/hypar-io/buildingblocks/blob/f5559af6f6d488711366531d2d3df2619d1d2212/Roof/RoofByDXF/test/_input/DXFLOG.TXT#L1)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think we don't need to include this log file in the repo.
</blockquote></details>

Ugh. Thanks DDS Viewer! You're a champ! (deleting).

**Review by anthonyhauck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/35)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @wynged)

___
*[Roof/RoofByDXF/test/_input/DXFLOG.TXT, line 1 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/35#-MIyVBt7-zFcmpzzSsD6:-MIyh7TgE1DGe1JEUUjq:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/f5559af6f6d488711366531d2d3df2619d1d2212/Roof/RoofByDXF/test/_input/DXFLOG.TXT#L1)):*
<details><summary><i>Previously, anthonyhauck (Anthony Hauck) wrote…</i></summary><blockquote>

Ugh. Thanks DDS Viewer! You're a champ! (deleting).
</blockquote></details>

Done.

**Review by wynged — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
