### PR TITLE
Add EmergencyEgress function to BuildingBlocks

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
Building Blocks contains many functions that are used in Hypar examples and in the Hypar tour. Please ensure that that following are true before granting this PR.

- [ ] The function has been deployed to dev.
- [ ] The function has been tested against the tour. If the function is not used in the tour, mark this as not applicable (NA).

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/95)

### CODE REVIEW

**Review by serenayl — CHANGES_REQUESTED** [review]
The `g.cs` dependency files are not committed but they are not gitignored either. Is it possible to do either one or the other?

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-:-N08RqnpCjrNDIIlM6tg:b-fb6pef)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @DmytroMuravskyi and @serenayl)

___
*[EmergencyEgress/src/EmergencyEgress.cs, line 114 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08U09z5_Nu9PQFaRKL:-N08U09z5_Nu9PQFaRKM:b-pmn6sp) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L114)):*
> ```Smalltalk
>         }
> 
>         //Create connection edges between corridors.
> ```

For methods, please use this format for Intellisense to pick up:

```
        /// <summary>
        /// 
        /// </summary>
```



_Code quote:_
```Smalltalk
        //Create connection edges between corridors.
        //Corridors itself are represented as middle lines without width.
        //For each line points are found with other corridors and itself that are closer that their combined width.
```
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 283 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VI6aAWqYfgznaRJm:-N08VI6aAWqYfgznaRJn:byo4crv) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L283)):*
> ```Smalltalk
>         }
> 
>         //There are no defined exits. in the room. Every segment middle point is considered.
> ```

Comment formatting



_Code quote:_
```Smalltalk
        //There are no defined exits. in the room. Every segment middle point is considered.
        //This is very simple approaches that ignores voids or obstacles inside room and
        //won't work for complex rooms.
```
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 308 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VuCjAxo1LQQ_kmlR:-N08VuCjAxo1LQQ_kmlS:bw9yhkx) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L308)):*
> ```Smalltalk
>                     foreach (var furthest in twoFurthest)
>                     {
>                         //Two reasons why room corners edges are shrined:
> ```

"are inset from the corners" feels like clearer documentation



_Code quote:_
```Smalltalk
are shrined
```
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 322 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VMna5nyBviDbhXpe:-N08VMna5nyBviDbhXpf:byo4crv) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L322)):*
> ```Smalltalk
>         }
> 
>         //Find if edge middle point is close enough to any corridor to be considered connected.
> ```

Comment formatting



_Code quote:_
```Smalltalk
//Find if edge middle point is close enough to any corridor to be considered connected.
```
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 406 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VNyG9yNUwvlGqUVH:-N08VNyG9yNUwvlGqUVI:byo4crv) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L406)):*
> ```Smalltalk
>         }
> 
>         //Add exit points to the grid
> ```

Comment formatting



_Code quote:_
```Smalltalk
//Add exit points to the grid
```
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 453 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VP8m-9DM8rTSbLrc:-N08VP8m-9DM8rTSbLrd:byo4crv) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L453)):*
> ```Smalltalk
>         }
> 
>         //For each room find exit that provides smallest distance for it's furthest corner.
> ```

Comment formatting



_Code quote:_
```Smalltalk
//For each room find exit that provides smallest distance for it's furthest corner.
```

**Review by DmytroMuravskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/95)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @serenayl)

___
*[EmergencyEgress/src/EmergencyEgress.cs, line 114 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08U09z5_Nu9PQFaRKL:-N0BO3n22FbTaxW7yJu5:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L114)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

For methods, please use this format for Intellisense to pick up:

```
        /// <summary>
        /// 
        /// </summary>
```
</blockquote></details>

Done.
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 283 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VI6aAWqYfgznaRJm:-N0BO4gVEIKLUkOTgeVh:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L283)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Comment formatting
</blockquote></details>

Done.
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 308 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VuCjAxo1LQQ_kmlR:-N0BO5MC4-vdrCBAmyEP:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L308)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

"are inset from the corners" feels like clearer documentation
</blockquote></details>

Done.
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 322 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VMna5nyBviDbhXpe:-N0BO5hRC53gV1BUvJvI:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L322)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Comment formatting
</blockquote></details>

Done.
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 406 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VNyG9yNUwvlGqUVH:-N0BO6CK6rOkCyciv7GI:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L406)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Comment formatting
</blockquote></details>

Done.
___
*[EmergencyEgress/src/EmergencyEgress.cs, line 453 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-N08VP8m-9DM8rTSbLrc:-N0BO6qv7gezGn192WkR:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/8dbacaae9619a8b3d850da991ac1c722e290bc60/EmergencyEgress/src/EmergencyEgress.cs#L453)):*
<details><summary><i>Previously, serenayl (Serena Li) wrote…</i></summary><blockquote>

Comment formatting
</blockquote></details>

Done.

**Review by serenayl — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Review by DmytroMuravskyi — COMMENTED** [review]
Since other functions have auto generated files included, I included them here as well

> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/95#-:-N0FZhVF8JeBVdU3t0wi:b4ibn8m)* status: 11 of 18 files reviewed, all discussions resolved (waiting on @serenayl)

**Review by serenayl — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Pull request merged**
