### PR TITLE
Fix creating core on the negative elevations

### PR DESCRIPTION
**Pull request by KaterynaSloboda**
- Fixed core creation on levels with negative elevation. Now it is possible to create a core even if there is no level with a positive elevation

Building Blocks contains many functions that are used in Hypar examples and in the Hypar tour. Please ensure that that following are true before granting this PR.

- [ ] The function has been published with staging, (but not released, until this PR is approved).
- [x] The function has been tested against the tour. If the function is not used in the tour, mark this as not applicable (NA).
- [ ] Strings in `hypar.json` have been translated to supported languages in the `messages` field.
- [ ] Any new project added to this repository has been added to BuildingBlocks.sln.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146)

### CODE REVIEW

**Review by anthonie-kramer — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146)* status: all files reviewed, 1 unresolved discussion (waiting on @KaterynaSloboda)

___
*[`Core/CoreByLevels/src/CoreMaker.cs` line 93 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146#-NZc8-asDIuQH_x6Ydia:-NZc8-asDIuQH_x6Ydib:boua3yw) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/5d0c69e8fa657979b5e2fe9a6c671dae2d7bc85d/Core/CoreByLevels/src/CoreMaker.cs#L93)):*
> ```Smalltalk
>             }
>             var shell = offShells.OrderByDescending(s => s.Area()).First();
>             var occArea = Levels.Sum(l => l.Perimeter.Area());
> ```

I would wrap these `.Area()` methods in a `Math.Abs()`. The current definition will return a negative `Area()` result if the `Polygon` is defined `Clockwise`. We will fix this in future versions of Elements, but I thought I would mention it since we are updating this function.

**Comment by KaterynaSloboda** [comment]
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146)_ status: all files reviewed, 1 unresolved discussion (waiting on @KaterynaSloboda)
> 
> _[`Core/CoreByLevels/src/CoreMaker.cs` line 93 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146#-NZc8-asDIuQH_x6Ydia:-NZc8-asDIuQH_x6Ydib:boua3yw) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/5d0c69e8fa657979b5e2fe9a6c671dae2d7bc85d/Core/CoreByLevels/src/CoreMaker.cs#L93)):_
> 
> > ```smalltalk
> >             }
> >             var shell = offShells.OrderByDescending(s => s.Area()).First();
> >             var occArea = Levels.Sum(l => l.Perimeter.Area());
> > ```
> 
> I would wrap these `.Area()` methods in a `Math.Abs()`. The current definition will return a negative `Area()` result if the `Polygon` is defined `Clockwise`. We will fix this in future versions of Elements, but I thought I would mention it since we are updating this function.

Done

**Review by anthonie-kramer — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146#-:-NZfrq1OEonYfEmG3gYf:b-uwkowd)* status: all files reviewed, 1 unresolved discussion (waiting on @KaterynaSloboda)

**Review by anthonie-kramer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KaterynaSloboda)

___
*[`Core/CoreByLevels/src/CoreMaker.cs` line 93 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146#-NZc8-asDIuQH_x6Ydia:-NZfrsOlASJw1EgMDS7F:bb6ywmx) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/5d0c69e8fa657979b5e2fe9a6c671dae2d7bc85d/Core/CoreByLevels/src/CoreMaker.cs#L93)):*
<details><summary><i>Previously, KaterynaSloboda wrote…</i></summary><blockquote>

Done
</blockquote></details>

LGTM

**Comment by KaterynaSloboda** [comment]
> Let me know once you have staged and tested the function, and then I will merge!
> 
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146#-:-NZfrxKuB7iwTkNKmodz:bnz1ynw)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KaterynaSloboda)

I don't have rights to edit this function. Here's a workflow with my tested copy of this feature: https://hypar.io/workflows/bb0070d3-4bf4-443f-9257-1e93b4866bb4

**Review by anthonie-kramer — APPROVED** [review]
I tested out the version that was published this morning, :lgtm_strong: 

I'll publish and merge these changes.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/146#-:-N_-SOzg0oz5YsTWRaTl:b-o5inoe)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KaterynaSloboda)

**Pull request merged**
