### PR TITLE
Update all functions to latest Elements

### PR DESCRIPTION
**Pull request by andrewheumann**
Continuing @ikeough's work to bring Building Blocks up to date in #121, this PR updates all functions to the latest versions of the Hypar Libraries, and resolves any build errors, with one exception*.

 Functions have *not* been `publish`ed, or tested in real workflows — this is *only* to ensure that they build.

*  ~~`EmergencyEgress` had some breaking changes I couldn't figure out how to resolve, but @DmytroMuravskyi is working on this.~~ Update: this is complete.
 
FUTURE WORK:
- Several functions in here are no longer useful for much, even if they build. Some (e.g. `RoofByDXF`) have actually been deleted from Hypar. We should do some cleaning and get rid of irrelevant functions, or at least mark them clearly if we want them to remain as code samples.
- Set up a mechanism to test all these functions 

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/123)

### CODE REVIEW

**Comment by ikeough** [comment]
I thought about adding `Hypar.Elements` to the `Directory.Build.props` file, so that we could control the version in one place, but it seems that your `update-all` script is probably a better route. What would be great to have on top of this is a test which integrates every function in Building Blocks, building a sort of proto building, that we could use as the smoke test that `update-all` hasn't broken anything.

**Comment by andrewheumann** [comment]
Agreed @ikeough, but I think that's more gardening time than I have space for right now. OK to leave as future work?

**Comment by ikeough** [comment]
Yes! Proceed.

**Review by katehryhorenko — APPROVED** [review]
> Reviewed 194 of 267 files at r2, 3 of 6 files at r4, 47 of 53 files at r5, 102 of 102 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrewheumann)

**Pull request merged**
