### PR TITLE
Fix Grid labeling lines with special ANSI characters.

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
Use excel style multiple letters in "{A}" labeling style.
Before
image
Now 
image

- [x] The function has been published with staging, (but not released, until this PR is approved).

- [x] The function has been tested against the tour. If the function is not used in the tour, mark this as not applicable (NA).

- [x] Strings in `hypar.json` have been translated to supported languages in the `messages` field.
No new fields added.

- [x] Any new project added to this repository has been added to BuildingBlocks.sln..

I added projects to the sln and published it. Feel free to merge it as I don't have a button to do so.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/136)

### CODE REVIEW

**Review by anthonie-kramer — APPROVED** [review]
:lgtm_strong: 

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/136#-:-NY0HVpjBL3h1XE1m_YL:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Review by anthonie-kramer — APPROVED** [review]
Thanks for adding to sln file!

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/136#-:-NY3oBDD-Ddscyux8Ti0:b-ytth91)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Comment by DmytroMuravskyi** [comment]
Is there anything preventing this PR from being merged?

**Review by anthonie-kramer — APPROVED** [review]
:lgtm: , feel free to merge

> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/136#-:-NYJDg17BJC80g7gRBVy:b-en3its)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Comment by DmytroMuravskyi** [comment]
I don't have write access to this repo, please merge this

**Pull request merged**
