### PR TITLE
Modify the roof function according to Bas requirements

### PR DESCRIPTION
**Pull request by andrzej-rudzki**
Building Blocks contains many functions that are used in Hypar examples and in the Hypar tour. Please ensure that that following are true before granting this PR.

- [x] The function has been deployed to dev.
- [ ] The function has been tested against the tour. If the function is not used in the tour, mark this as not applicable (NA).

---
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106)

### CODE REVIEW

**Review by wynged — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106)* status: all files reviewed, 8 unresolved discussions (waiting on @andrzej-rudzki)

___
*[`Roof/Roof/hypar.json` line 104 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_3fkQ4kRIJ1q5CRU_:-N4_3fkQ4kRIJ1q5CRUa:b-o1wmix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/hypar.json#L104)):*
> ```JSON
>         "minimum": 0.05
>       },
>       "Change Roof Level": {
> ```

can we rename this to "Keep Roof Below Envelope" ?
___
*[`Roof/Roof/hypar.json` line 111 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_3msc9iGWL1J-C1sb:-N4_3msc9iGWL1J-C1sc:b-cyanvo) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/hypar.json#L111)):*
> ```JSON
>       },
>       "Insulation Color": {
>         "default": {
> ```

this schema has been expanded for some reason, it should just stay as `        "$ref": "https://hypar.io/Schemas/Geometry/Color.json"` like the color property use to be.  Can you try to use `$ref` again and confirm that this is happening automatically for some reason?
___
*[`Roof/Roof/dependencies/Roof.cs` line 10 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_1ujR95wWBMvCiyQM:-N4_1ujR95wWBMvCiyQN:b-d6eg1g) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/dependencies/Roof.cs#L10)):*
> ```Smalltalk
>     {
>         public static Material RoofMaterial { get; set; } = new Material("Roof", Colors.Gray, 0.1, 0.1, null);
>         public static Material InstallationMaterial { get; set; } = new Material("Installation", Colors.Yellow, 0.1, 0.1, null);
> ```

spelling.  "Insulation "  not installation
___
*[`Roof/Roof/dependencies/Roof.cs` line 11 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_23zABco7HbHUqhGe:-N4_23zB3H6hp-YGXeGl:bgv9fe1) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/dependencies/Roof.cs#L11)):*
> ```Smalltalk
>         public static Material RoofMaterial { get; set; } = new Material("Roof", Colors.Gray, 0.1, 0.1, null);
>         public static Material InstallationMaterial { get; set; } = new Material("Installation", Colors.Yellow, 0.1, 0.1, null);
>         public Roof(Profile p, double thickness, Transform t, bool isInstallation = false) : this(p, p.Area(), t, isInstallation? InstallationMaterial: RoofMaterial , new Representation(new List<SolidOperation>()))
> ```

insulation spelling.
___
*[`Roof/Roof/src/RoofFunction.cs` line 149 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_2NS86BnA_93eG01S:-N4_2NS86BnA_93eG01T:b-3zjp4u) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L149)):*
> ```Smalltalk
>         }
> 
>         private static Roof createRoofAndInstallation(Profile profile, RoofFunctionInputs input, RoofFunctionOutputs output, Transform polygonTransform)
> ```

capatalize this method.
___
*[`Roof/Roof/src/RoofFunction.cs` line 155 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_3QpH26z9K7s4TAT5:-N4_3QpH26z9K7s4TAT6:b-peqf7z) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L155)):*
> ```Smalltalk
>             {
>                 polygonTransform.Move(new Vector3(0, 0, -input.RoofThickness - input.InsulationThickness));
>                 installationTransform.Move(new Vector3(0, 0, -input.RoofThickness - input.InsulationThickness));
> ```

spelling "insulation"
___
*[`Roof/Roof/src/RoofFunction.cs` line 158 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_2jX744cddEE75Our:-N4_2jX744cddEE75Ous:b-dwrckr) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L158)):*
> ```Smalltalk
>             }
>             var roof = new Roof(profile, input.RoofThickness, polygonTransform,false);
>             output.Model.AddElement(roof);
> ```

I think it would  be better to return multiple roofs from this function rather than passing the output in as an argument.  Lets make this function return `Roof[]` and then add all of the created roofs to the model at the same time using `output.Model.AddElements(createdRoofs)`
___
*[`Roof/Roof/src/RoofFunction.cs` line 159 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_2dDe1ANfqx8N0brd:-N4_2dDe1ANfqx8N0bre:bnamblj) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L159)):*
> ```Smalltalk
>             var roof = new Roof(profile, input.RoofThickness, polygonTransform,false);
>             output.Model.AddElement(roof);
>             var installationRoof = new Roof(profile, input.InsulationThickness, installationTransform,true);
> ```

What if  there is no insulation?  let's at least say that if insullation is 0 then it is not created.

**Review by andrzej-rudzki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106)* status: all files reviewed, 8 unresolved discussions (waiting on @wynged)

___
*[`Roof/Roof/hypar.json` line 104 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_3fkQ4kRIJ1q5CRU_:-N4exWlY2nj6DRYRgj-b:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/hypar.json#L104)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

can we rename this to "Keep Roof Below Envelope" ?
</blockquote></details>

Done.
___
*[`Roof/Roof/hypar.json` line 111 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_3msc9iGWL1J-C1sb:-N4f3EwW5-0p1yrNTGz_:b-f8lxy) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/hypar.json#L111)):*
> Keep Roof Below Envelope
This code is generated automatically after using pull, I revert this
___
*[`Roof/Roof/dependencies/Roof.cs` line 10 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_1ujR95wWBMvCiyQM:-N4f5Ruq2c6B2uVClO9j:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/dependencies/Roof.cs#L10)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

spelling.  "Insulation "  not installation
</blockquote></details>

Done.
___
*[`Roof/Roof/dependencies/Roof.cs` line 11 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_23zABco7HbHUqhGe:-N4f5UVSDjka_JESEL-g:b-awpyft) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/dependencies/Roof.cs#L11)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

insulation spelling.
</blockquote></details>

I've changed it everywhere
___
*[`Roof/Roof/src/RoofFunction.cs` line 149 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_2NS86BnA_93eG01S:-N4f5soGAzG2iwPd_BlV:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L149)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

capatalize this method.
</blockquote></details>

Done.
___
*[`Roof/Roof/src/RoofFunction.cs` line 155 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_3QpH26z9K7s4TAT5:-N4f5uPFD3sThPIlucZj:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L155)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

spelling "insulation"
</blockquote></details>

Done.
___
*[`Roof/Roof/src/RoofFunction.cs` line 158 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_2jX744cddEE75Our:-N4f9Z1h-9K-_ey_QmBm:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L158)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

I think it would  be better to return multiple roofs from this function rather than passing the output in as an argument.  Lets make this function return `Roof[]` and then add all of the created roofs to the model at the same time using `output.Model.AddElements(createdRoofs)`
</blockquote></details>

Done.
___
*[`Roof/Roof/src/RoofFunction.cs` line 159 at r1](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4_2dDe1ANfqx8N0brd:-N4fAEL91J4TAbwOCq4z:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/9cd27119cea559d2b257b7a9d41e0010992bd3d3/Roof/Roof/src/RoofFunction.cs#L159)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

What if  there is no insulation?  let's at least say that if insullation is 0 then it is not created.
</blockquote></details>

Done.

**Review by andrzej-rudzki — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106)* status: all files reviewed, 8 unresolved discussions (waiting on @wynged)

**Review by andrzej-rudzki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @wynged)

___
*[`Roof/Roof/src/RoofFunction.cs` line 163 at r2](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4glXEo-G0cG_WX7tsi:-N4hvofz8GhLMekkuHFc:bni31vg) ([raw file](https://github.com/hypar-io/buildingblocks/blob/ef7d58b8accba473262cc47d14b4b77c5d530be0/Roof/Roof/src/RoofFunction.cs#L163)):*
> ApproximatelyEquals
Done: but I'm not sure why we need to apply a tolerance to the input. For output, I understand that tolerance is needed.
___
*[`Roof/Roof/src/RoofFunction.cs` line 165 at r2](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-N4gljii5z1VsbkpX_DA:-N4kPA_77F1QFUoN2-Qd:b-896fix) ([raw file](https://github.com/hypar-io/buildingblocks/blob/ef7d58b8accba473262cc47d14b4b77c5d530be0/Roof/Roof/src/RoofFunction.cs#L165)):*
<details><summary><i>Previously, wynged (Eric Wassail) wrote…</i></summary><blockquote>

when we create the insullation, can we give it a reference to Roof that it corresponds to?  that will make navigation in the UI much easier,  because you can bound between Insulation and roof.   Look at where we do something similar on line 93.
</blockquote></details>

Done.

**Review by andrzej-rudzki — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106#-:-N4kP_AX8_4E_irhsR7z:bb6un1j)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @wynged)

**Review by wynged — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/buildingblocks/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrzej-rudzki)

**Pull request merged**
