### PR TITLE
updating structure to handle error from bays

### PR DESCRIPTION
**Pull request by anthonie-kramer**
BACKGROUND:
The `Structures` function was not handling an error with the incoming `CellComplexes` from the `Bays` function due to an empty list.

DESCRIPTION:
I have added a check for this dependency and returned an error message to the user when it is missing.

TESTING:
This workflow (originally from the hy-ccup) shows the error that describes the missing `CellComplexes` from `Bays`
https://hypar.io/workflows/fc153bc3-3de5-4748-82ac-880ff682e3cb

FUTURE WORK:
It would be nice someday to be able to match up missing dependency context with common errors like an empty list and provide a general solution for the error message.

BUILDING BLOCKS CHECKS:
Building Blocks contains many functions that are used in Hypar examples and in the Hypar tour. Please ensure that that following are true before granting this PR.

- [x] The function has been published with staging, (but not released, until this PR is approved).
- [x] The function has been tested against the tour. If the function is not used in the tour, mark this as not applicable (NA).
- [x] Strings in `hypar.json` have been translated to supported languages in the `messages` field.
- [x] Any new project added to this repository has been added to BuildingBlocks.sln.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/131)

### CODE REVIEW

**Comment by HyparJonathan** [comment]
*[`Structure/StructureByEnvelope/src/Structure.cs` line 67 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/131#-NUXcvTBCjCw8s1RuXpW:-NUXcvTBCjCw8s1RuXpX:brxj5y7) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/2472363140d508adbbefbc6e11e81484e0f77177/Structure/StructureByEnvelope/src/Structure.cs#L67)):*
> ```Smalltalk
>                 {
>                 cellComplex = cellComplexes.First();
>                 }
> ```

Hello! It's my first substantive review, but so far I have only nits and questions.

First, I see weird indentation, and it raises the question of whether Hypar has standardized on a style guide for each language, and, if so, whether formatting like this can be handled by tooling (so that there can be no time wasted in review making decisions).

Second, also a style thing, I'd be inclined to drop the else clause after a return.



_Code quote:_
```Smalltalk
                if(cellComplexes.Count() == 0)
                {
                    output.Errors.Add($"No CellComplexes found in the model '{BAYS_MODEL_NAME}'. Check the output from the function upstream that has a model output '{BAYS_MODEL_NAME}'.");
                    return output;
                }
                else
                {
                cellComplex = cellComplexes.First();
                }
```

**Review by HyparJonathan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/131)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @anthonie-kramer)

**Review by anthonie-kramer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/131)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @HyparJonathan)

___
*[`Structure/StructureByEnvelope/src/Structure.cs` line 67 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/131#-NUXcvTBCjCw8s1RuXpW:-NUYlIvv3OWeIi2wWoDd:b-hmapw5) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/2472363140d508adbbefbc6e11e81484e0f77177/Structure/StructureByEnvelope/src/Structure.cs#L67)):*
<details><summary><i>Previously, HyparJonathan wrote…</i></summary><blockquote>

Hello! It's my first substantive review, but so far I have only nits and questions.

First, I see weird indentation, and it raises the question of whether Hypar has standardized on a style guide for each language, and, if so, whether formatting like this can be handled by tooling (so that there can be no time wasted in review making decisions).

Second, also a style thing, I'd be inclined to drop the else clause after a return.
</blockquote></details>

Great points!

1. I realize now that I turned off the VS Code `Format On Save` setting when I was working on this (due to an unrelated formatting frustration elsewhere). We do encourage this to be enabled as detailed on the `Machine Setup` notion page: https://www.notion.so/hyparaec/Machine-setup-9bfcd5da5a01485abec88fcec944995e?pvs=4#4b166eb91d274f4596f5ce260b4c287b

2. Completely agree with dropping the `else` since I `return` in the `if` statement above.

I will fix the formatting and push an update shortly

**Review by HyparJonathan — APPROVED** [review]
:lgtm: with caveat that I am very :man_shrugging: for semantics, culture, and best practices. 

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/131#-:-NUb3TiI-VpMq2BP5BdY:bfi5ju9)* status: 10 of 11 files reviewed, 1 unresolved discussion

**Pull request merged**
