### PR TITLE
Envelope By Site overrides modernization

### PR DESCRIPTION
**Pull request by srudenkoamc**
- Envelope By Site function now uses Apply for overrides handling.
- Added a test for overrides.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141)

### CODE REVIEW

**Review by DmytroMuravskyi — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @anthonie-kramer and @srudenkoamc)

___
*[`Envelope/EnvelopeBySite/src/EnvelopeBySite.cs` line 12 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-NZ59jDc6VpV1DRCF1K9:-NZ59jDc6VpV1DRCF1KA:brf6jdm) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/0ee88f3adf0189612892e377d6aa8624caa4beda/Envelope/EnvelopeBySite/src/EnvelopeBySite.cs#L12)):*
> ```Smalltalk
>     public static class EnvelopeBySite
>     {
>         private static readonly Plane XY_PLANE = new((0, 0, 0), (0, 0, 1));
> ```

There is already static Plane.XY in Elements
___
*[`Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest/model_dependencies/Site/befa47f9-51c7-4873-bc62-afd5c591b4fd.json` line 0 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-NZ59nvc4yQLq5R4P174:-NZ59nvc4yQLq5R4P175:b-8nnkkx) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/0ee88f3adf0189612892e377d6aa8624caa4beda/Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest/model_dependencies/Site/befa47f9-51c7-4873-bc62-afd5c591b4fd.json#L0)):*
Not used

**Comment by srudenkoamc** [comment]
https://github.com/hypar-io/BuildingBlocks/pull/141#pullrequestreview-1504771854 is resolved in https://github.com/hypar-io/BuildingBlocks/pull/141/commits/80a0afbc4b4c04c4c823b3df5bf3bc4a22827bcd.

**Review by srudenkoamc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @anthonie-kramer and @DmytroMuravskyi)

___
*[`Envelope/EnvelopeBySite/src/EnvelopeBySite.cs` line 12 at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-NZ59jDc6VpV1DRCF1K9:-NaLodAjDjpuyrx2Z_uM:b-896fix) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/0ee88f3adf0189612892e377d6aa8624caa4beda/Envelope/EnvelopeBySite/src/EnvelopeBySite.cs#L12)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

There is already static Plane.XY in Elements
</blockquote></details>

Done.
___
*[`Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest/model_dependencies/Site/befa47f9-51c7-4873-bc62-afd5c591b4fd.json` line  at r1](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-NZ59nvc4yQLq5R4P174:-NaLp5WD1N1WkAOQ_6gA:b-896fix) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/0ee88f3adf0189612892e377d6aa8624caa4beda/Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest/model_dependencies/Site/befa47f9-51c7-4873-bc62-afd5c591b4fd.json#L)):*
<details><summary><i>Previously, DmytroMuravskyi wrote…</i></summary><blockquote>

Not used
</blockquote></details>

Done.

**Review by katehryhorenko — APPROVED** [review]
one small comment

> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-:-Ng-FzF20v8q8DDi79Ig:b302opz)* status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @anthonie-kramer, @DmytroMuravskyi, and @srudenkoamc)

___
*[`Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest.cs` line 78 at r4](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-Ng-FsDO5YDizIyGjbZD:-Ng-FsDO5YDizIyGjbZE:bvpc80j) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/b02dde82acea57c6eafceb93fa0daa1066600a9c/Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest.cs#L78)):*
> ```Smalltalk
>             }
> 
>             //result.Model.ToGlTF("../../../EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest/results/EnvelopeBySiteOverridesTest.gltf", false);
> ```

Please delete commented code

**Comment by srudenkoamc** [comment]
> one small comment
> 
> > _[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-:-Ng-FzF20v8q8DDi79Ig:b302opz)_ status: 4 of 10 files reviewed, 3 unresolved discussions (waiting on @anthonie-kramer, @DmytroMuravskyi, and @srudenkoamc)
> 
> _[`Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest.cs` line 78 at r4](https://reviewable.io/reviews/hypar-io/BuildingBlocks/141#-Ng-FsDO5YDizIyGjbZD:-Ng-FsDO5YDizIyGjbZE:bvpc80j) ([raw file](https://github.com/hypar-io/BuildingBlocks/blob/b02dde82acea57c6eafceb93fa0daa1066600a9c/Envelope/EnvelopeBySite/test/EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest.cs#L78)):_
> 
> > ```smalltalk
> >             }
> > 
> >             //result.Model.ToGlTF("../../../EnvelopeBySiteOverridesTest/EnvelopeBySiteOverridesTest/results/EnvelopeBySiteOverridesTest.gltf", false);
> > ```
> 
> Please delete commented code

Done at https://github.com/hypar-io/BuildingBlocks/pull/141/commits/570836f3ab9d15fbf7a049a7c512b553675ff3e2

**Pull request merged**
