### PR TITLE
Dmuravskyi/schemas no changes

### PR DESCRIPTION
**Pull request by DmytroMuravskyi**
Next function schemas are updated without logic change:
ColumnsByFloors, EmergencyEgress, Walls, StructureByEnvelope, Site, FloorsByLevels, FloorsBySketch, Grid, People.

- - -
This change is [Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/142)

### CODE REVIEW

**Review by anthonie-kramer — APPROVED** [review]
:lgtm: 

> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/142#-:-NZc48DpBnOdJ1ouvYIB:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Review by anthonie-kramer — APPROVED** [review]
Let me know if you have staged these for testing and tested them out and then I will merge

> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/142#-:-NZc4BtL835G3fr2-b5H:bz1n9co)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Comment by DmytroMuravskyi** [comment]
I've checked and published every function from here and others PRs with at least one .cs fie changed. There is open question with Site - its deprecated property causes issues, will discuss the situation today and post another commit.

**Comment by DmytroMuravskyi** [comment]
Let's wait until I refresh Polygon autogenerated file for other functions in all PRs as well

**Review by anthonie-kramer — COMMENTED** [review]
Sounds good. Let me know when they are good to go.

> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/142#-:-NZfrU9j2-ugxyTFp6jc:b-qkr9rm)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Comment by DmytroMuravskyi** [comment]
I updated all Polygon autogenerated files, PRs are ready

**Review by anthonie-kramer — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hypar-io/BuildingBlocks/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DmytroMuravskyi)

**Pull request merged**
